[default]
extend-ignore-identifiers-re = [
    "SerDes",
    "DuPont",
    "g3caf61a44c2",
    "des3_ede",
    "hda",
    "noe",
    "NOE",
    "BA",
    "lin2-rin2"
]
extend-ignore-re = [
    "lin2-rin2",
    "certifi",
    "python-certifi-win32",
    "SHW"
]
